[versions]
spring-boot-starter = "3.0.0"
lombok = "1.18.22"
kafka = "3.3.1"
kafka-streams = "3.3.1"
spring-kafka = "3.0.0"
spock = "2.0-groovy-3.0"
junit = "4.13.2'"
groovy = "3.0.8"

[libraries]
spring-boot-starter = {module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot-starter" }
spring-boot-starter-test = {module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot-starter" }

lombok = {module = "org.projectlombok:lombok", version.ref = "lombok"}

kafka = {module = "org.apache.kafka:kafka-clients", version.ref = "kafka"}
kafka-streams = {module = "org.apache.kafka:kafka-streams", version.ref = "kafka-streams"}
spring-kafka = {module = "org.springframework.kafka:spring-kafka", version.ref = "spring-kafka"}
spring-kafka-test = {module = "org.springframework.kafka:spring-kafka-test", version.ref = "spring-kafka"}

spock = {module = "org.spockframework:spock-core", version.ref = "spock"}
junit = {module = "junit:junit", version.ref = "junit"}

groovy = {module = "org.codehaus.groovy:groovy-all", version.ref = "groovy"}
